### ISSUE TITLE
RAML Trype for Edm.DateTimeOffset is Wrong

### ISSUE THREAD

**Issue by JosephAllen** [mulesoft/docs-apikit#62]
The RAML type for Edm.DateTimeOffset should be `date-only`

**Comment by Crispy-Salesforce** [comment]
@JosephAllen, we are closing this contribution because it has exceeded the age limit for a timely merge.
If the contribution is still valid, please, open a separate GitHub issue or pull request and we will work on it as soon as possible.
Thanks!
