### ISSUE TITLE
W-13498349-Outdated description "Create an APIkit for SOAP Project"

### ISSUE THREAD

**Issue by hansjakobli** [mulesoft/docs-apikit#76]
It appears as it is no longer possible to reference a WSDL when creating a Mule Project.
What has worked for me is to copy the WSDL into the `src/main/resources/api` folder, then right click onto the .wsdl and select "Mule" -> "Generate Flows from WSDL".

Also the title should be fixed as we don't create an APIkit, we rather create a SOAP Project using APIkit.

**Comment by Crispy-Salesforce** [comment]
@hansjakobli, thanks for contacting us!
Please, let us tell you that we have created W-13498349 to work on your collaboration.
Do not hesitate in contacting us in case you need any further assistance regarding this or any other topic.
BR,
Cristian Pose

**Comment by Crispy-Salesforce** [comment]
Dear, @hansjakobli:
We analyzed your comments and we would like to share some information with you.
Do you mean that you can not select the WSDL file from Studio? If so, let us tell you that you can choose a WSDL file from the "Import RAML from local file" tab in the "New Mule Project" window. 
Do you mean that no WSDL file is created? The WSDL file should be downloaded or created beforehand as part of the SOAP prerequisites to create a SOAP project.
If the information provided is not enough, please, contact our support team and they will be glad to help you.
If you have comments on our documentation, please, feel free to collaborate through a pull request so we can easily identify the topic.
We will close this issue now but do not hesitate to contact us in case you need any further assistance.
Thanks for your collaboration!
BR,
Cristian Pose
