### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by germancorbettamulesoft** [mulesoft/docs-apikit#9]
The two links of the "To Meet Prerequisites for Using APIkit for Soap" documentation are not working. 

1) https://docs.mulesoft.com/apikit/v/4.x/_attachments/tshirt2.wsdl

2) https://docs.mulesoft.com/apikit/v/4.x/_attachments/apikit-for-soap-tutorial.xml

WebPage: https://docs.mulesoft.com/apikit/4.x/apikit-4-soap-prerequisites-task

**Comment by damiancalabresi** [comment]
Same issue here, these links are not working

**Comment by Crispy-Salesforce** [comment]
@damiancalabresi, we are closing this contribution because it has exceeded the age limit for a timely merge. 
If the contribution is still valid, please, open a separate GitHub issue or pull request.
Thanks!
